
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icensnfvrjxjszobsogk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZW5zbmZ2cmp4anN6b2Jzb2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODU1MzIsImV4cCI6MjA2MjA2MTUzMn0.L96rWnMI5bP2B3PoCye1-AGk5-6d5sK7TQbi6lXziwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log('Inicializando cliente Supabase para o projeto:', SUPABASE_URL);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, 
    storageKey: 'hubb-assist-auth-storage',
    autoRefreshToken: true,
    flowType: 'pkce',
    autoConfirmNewUsers: true, // Automatically confirm new users
    debug: true // Ativar logs de debug para autenticação
  }
});

// Verificar a conexão ao inicializar
(async () => {
  const { data, error } = await supabase.from('patients').select('count').limit(1);
  console.log('Teste de conexão com Supabase:');
  console.log('- Resultado:', data);
  if (error) {
    console.error('- Erro na conexão:', error);
  } else {
    console.log('- Conexão bem-sucedida');
  }
})();
